version: '3.8'

services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - CADDY_DOCKER_SOCK_PATH=/var/run/docker.sock
      - CADDY_TLS_INTERNAL=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy-data:/data
      - ./caddy-config:/config
    networks:
      - portainer-apps

networks:
  portainer-apps:
    external: true
