services:
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    ports:
      - "${PORT:-1111}:80"  # External → Internal:80 (it-tools web interface)
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ${DATA_PATH:-./data}:/app/data

    networks:
      - portainer-apps

networks:
  portainer-apps:
    external: true
