version: '3.8'

services:
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    ports:
      - "10080:80"
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/app/data
#     networks:
#       - portainer-apps

# networks:
#   portainer-apps:
#     external: true
