version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "10001:9001" # External:10001 → Internal:9001 (MinIO Console - exposed via Caddy)
      - "9000:9000"  # External:9000 → Internal:9000 (MinIO S3 API)
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ${MINIO_DATA_PATH:-/minio-s3}:/data
    command: server /data --console-address ":9001"
    networks:
      - portainer-apps

networks:
  portainer-apps:
    external: true
